task: sentence-transformers:pair_score
base_model: microsoft/mpnet-base
project_name: autotrain-st-pair-score-local-dataset
log: tensorboard
backend: local

data:
  path: /path/to/your/dataset # this must be the path to the directory containing the train and valid files
  train_split: train # this is the name of the train file (csv or jsonl)
  valid_split: null # this is the name of the valid file (csv or jsonl), optional
  column_mapping:
    sentence1_column: input_sentence
    sentence2_column: target_sentence
    target_column: score

params:
  max_seq_length: 512
  epochs: 5
  batch_size: 8
  lr: 2e-5
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true