task: sentence-transformers:qa
base_model: microsoft/mpnet-base
project_name: autotrain-st-qa
log: tensorboard
backend: local

data:
  path: sentence-transformers/natural-questions
  train_split: train
  valid_split: null
  column_mapping:
    sentence1_column: query
    sentence2_column: answer

params:
  max_seq_length: 512
  epochs: 5
  batch_size: 8
  lr: 2e-5
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true